---
title: "Run"
format: html
editor: visual
---

-   generate simulated data
-   fit null model
-   parametric bootstrap
-   output power curve

```{r}
library(tidyverse)
library(fda)
library(ggplot2)
library(stats)
library(roll)
```

# Functions to Generate Simulated Data

## Generate state function

```{r}
### Simulate data function

# coefficient parameters
# n = 500
# nb = 25
# sd0 = 2
# d = 1
# p = 2.5


# ARMA noise parameters (Low SNR)
# lambda_target = 0.5
# ar.coefs = c(0.8, 0.1)
# ma.coefs = c(0.3)
# window = 30
# plotit = TRUE

# Function to create noise
generate_state <- function(n = 500,
                           plotit = FALSE,
                           nb = 25,
                           sd0 = 2,
                           d = 1,
                           p = 2.5,
                           lambda_target = 0.5,
                           ar.coefs = c(0.8, 0.1),
                           ma.coefs = c(0.3),
                           window = 30) {
  
  # simulate random periodic drift
  fb <- create.fourier.basis(rangeval = c(0, n), nbasis = nb, period = n)

  # generate two coefficient sets at distance d
  # create first set of fourier coefficients
  K <- (nb - 1) / 2
  k <- rep(1:K, each = 2) # coefficient index vector
  sd_k <- sd0 / (k^p)
  coef1 <- rnorm(2 * K, mean = 0, sd = sd_k)

  # create second set of coefficients
  # uniform sphere direction
  z <- rnorm(length(coef1))
  u <- z / sqrt(sum(z^2)) # unit length
  # ellipsoid axes (decay structure that is a function of distance)
  axes <- 1 / (1:length(coef1))^(p - 0.1 * d)
  # scale to ellipse
  dir <- u * axes
  # renormalize
  dir <- dir / sqrt(sum(dir^2))
   # shift by d
  coef2 <- coef1 + d * dir

  # construct trends
  x1 <- (eval.basis(1:n, basisobj = fb)[, -1] %*% coef1) |> scale()
  x2 <- (eval.basis(1:n, basisobj = fb)[, -1] %*% coef2) |> scale()

  # compute ARMA autocovariance structure
  # ARMAacf can return theoretical autocorrs for ARMA given noise variance
  rho <- ARMAacf(ar = ar.coefs, ma = ma.coefs, lag.max = (window - 1))
  psi <- ARMAtoMA(ar = ar.coefs, ma = ma.coefs, lag.max = 200)

  # contains all MA coeffs
  psi_full <- c(1, psi)

  # gamma0 when innovation variance is assumed 1,(because variance is
  # scaled linearly and we can separate arma shape from noise magnitude)
  gamma0_unit <- sum(psi_full^2) # gamma(0) when sigma^2 = 1
  gamma_unit <- gamma0_unit * rho # gamma(k) when sigma^2 = 1

  # making k vector to iterate over
  k <- 1:(window - 1)
  # Equation for variance of MA of length W of a stationary process
  # plugging in gamma_unit which assumes innovation variance = 1
  sigma2_window_mean_unit <- (1 / window^2) * (window * gamma_unit[1] + 2 *
    sum((window - k) * gamma_unit[k + 1]))

  # fix S2_y to make it mean of sd of each series over a rolling time k
  # rolling average of each series
  loc_var_x1 <- roll_var(x1, width = window, center = TRUE, min_obs = 2)
  s2_y_obs_x1 <- mean(loc_var_x1, na.rm = TRUE)

  loc_var_x2 <- roll_var(x2, width = window, center = TRUE, min_obs = 2)
  s2_y_obs_x2 <- mean(loc_var_x2, na.rm = TRUE)


  # scale innovation sd for each series
  sigma2_x1 <- s2_y_obs_x1 / (lambda_target * sigma2_window_mean_unit)
  sigma_x1 <- sqrt(sigma2_x1)

  sigma2_x2 <- s2_y_obs_x2 / (lambda_target * sigma2_window_mean_unit)
  sigma_x2 <- sqrt(sigma2_x2)

  noise1 <- arima.sim(
    model = list(order = c(length(ar.coefs), 0, length(ma.coefs)), 
                 ar = ar.coefs, ma = ma.coefs),
    n = n,
    rand.gen = function(t) {
      rnorm(t, mean = 0, sd = sigma_x1)
    },
    n.start = 100
  )

  noise2 <- arima.sim(
    model = list(order = c(length(ar.coefs), 0, length(ma.coefs)), 
                 ar = ar.coefs, ma = ma.coefs),
    n = n,
    rand.gen = function(t) {
      rnorm(t, mean = 0, sd = sigma_x2)
    },
    n.start = 100
  )

  # add noise to drift
  y1 <- x1 + noise1
  y2 <- x2 + noise2

  if (plotit) {
    ylim <- c(-1.1, 1.1) * max(abs(c(x1, y1, y2)))
    plot(x1, type = "l", ylim = ylim)
    lines(y1, col = "red")
    lines(y2, col = "blue")
  }

  out <- list(y1 = y1, y2 = y2)
}
```


### Graph data
```{r}
x <- generate_state(d = 1, plotit = TRUE)
```


### d simulation

```{r}
# N: number of simulations for each value of d
d_sim <- function(N = 5, d = 1) {
  
  results <- list()

  for (i in 1:N) {
    cat("\nRunning simulation", i, "of", N, " for d-value = ", d, "\n")
    flush.console()

    x <- generate_state(
      n = 500,
      plotit = FALSE,
      nb = 25,
      sd0 = 2,
      d = d,
      p = 2.5,
      lambda_target = 0.5,
      ar.coefs = c(0.8, 0.1),
      ma.coefs = c(0.3),
      window = 30
    )

    nullmodel <- fit_null_model(x$y1,
      x$y2,
      q = NULL,
      h = NULL,
      alpha = 0.05,
      rho0 = 0,
      max_pq = 2
    )

    boot <- bootstrap_local_corr(nullmodel)

     results[[i]] <- data.frame(
      d = d,
      sim_n = i,
      entry_rate = boot[["expected_asymptotic"]][["entry_rate"]],
      p.entry = boot[["p_values"]][["entry_rate"]],
      mean_run_length = boot[["expected_asymptotic"]][["mean_run_length"]],
      p.length = boot[["p_values"]][["mean_run_length"]]
    )
     
  }
  bind_rows(results)
}
```



```{r}
#| message: false
d_vals <- c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
d_data <- map_dfr(d_vals, ~ d_sim(N = 100, d = .x))

 write_csv(d_data, "sim0-10_N100.csv")

```


### Plots
```{r}
d_data <- read_csv(here::here("sim0-10_N100.csv"))


new <- d_data |>
  mutate(reject_entry = case_when(
    p.entry >= 0.05 ~ "no",
    p.entry < 0.05 ~ "yes"
  ),
  reject_length = case_when(
    p.length >= 0.05 ~ "no",
    p.length < 0.05 ~ "yes")
  ) |>
  group_by(d) |>
  summarise(
    n_sim = n(),                           
    n_reject1 = sum(reject_entry == "yes", na.rm = TRUE),
    n_reject2 = sum(reject_length == "yes", na.rm = TRUE),
    prop_reject_entry = n_reject1 / n_sim,
    prop_reject_length = n_reject2 / n_sim        
  ) |>
  ungroup() |>
  mutate(
    var_entry = (prop_reject_entry * (1 - prop_reject_entry)) / n_sim,
    se_entry  = sqrt(var_entry),
    var_length =  (prop_reject_length * (1 - prop_reject_length)) / n_sim,
    se_length  = sqrt(var_length),
  )




p1 <- new |>
  ggplot(aes(x = d, y = prop_reject_entry)) +
  geom_point(size = 5) +
  geom_errorbar(
    aes(
      ymin = prop_reject_entry - se_entry,
      ymax = prop_reject_entry + se_entry
    ),
    width = 0.2
  ) +
  geom_smooth(se = FALSE) +
  theme_minimal(base_size = 18) +
  labs(title = "Entry Rate",
       x = "d value",
       y = "",
       subtitle = "P(reject)") +
  scale_x_continuous(breaks = scales::breaks_width(1)) +  
  theme(
    plot.title = element_text(size = 22),
    axis.title.x = element_text(size = 18),
    axis.text = element_text(size = 18),
    panel.grid.minor = element_blank()
  )

p1





p2 <- new |>
ggplot(aes(x = d, y = prop_reject_length)) +
  geom_point(size = 5) +
  geom_errorbar(
    aes(
      ymin = prop_reject_length - se_length,
      ymax = prop_reject_length + se_length
    ),
    width = 0.2
  ) +
  geom_smooth(se = FALSE) +
  geom_smooth(se = FALSE) +
  theme_minimal(base_size = 18) +
  labs(title = "Length",
       x = "d value",
       y = "",
       subtitle = "P(reject)") +
  scale_x_continuous(breaks = scales::breaks_width(1)) +  
  theme(
    plot.title = element_text(size = 22),
    axis.title.x = element_text(size = 18),
    axis.text = element_text(size = 18),
    panel.grid.minor = element_blank()
  )

p2

```

# States with Decoupling Rates

### Generate with rates
```{r}

generate_lambda <- function(n,
                            decouple_rate     = 0.1,  
                            decouple_strength = 1,
                            seed              = NULL) {
  if (!is.null(seed)) set.seed(seed)
  
  n_events        <- min(3, floor(1 / decouple_rate))
  gap             <- n / n_events
  decouple_length <- round(gap * decouple_rate)  # wider as rate increases
  events          <- round(seq(from = gap / 2, by = gap, length.out = n_events))
  
  t      <- 1:n
  lambda <- rep(1, n)
  
  for (i in events) {
    bump   <- dnorm(t, mean = i, sd = decouple_length / 4)
    bump   <- bump / max(bump)
    lambda <- lambda - decouple_rate * decouple_strength * bump
  }
  
  pmax(0, pmin(1, lambda))
}


generate_fourier_coef <- function(nb, sd0 = 2, p=2.5) {
  K <- (nb - 1) / 2
  k <- rep(1:K, each = 2) #coefficient index vector
  sd_k <- sd0 / (k^p) 
  rnorm(2 * K, mean = 0, sd = sd_k)
}
 

# Function to create noise
generate_state_rate <- function(n = 500,
                           nb = 25,
                           sd0 = 2,
                           p = 2.5,
                           decouple_rate = 0.5,  
                           decouple_strength = 1,
                           
                           lambda_target = 0.5,
                           ar.coefs = c(0.8, 0.1),
                           ma.coefs = c(0.3),
                           window = 30,
                           plotit = FALSE
                           ) {
  
  
  
  
  coef1 <- generate_fourier_coef(nb)
  coef2 <- numeric(24)
  coef2[1] <-1
  
  lambda <- generate_lambda(n, decouple_rate, decouple_strength)
  
  fb  <- create.fourier.basis(rangeval = c(0, n), nbasis = nb, period = n)
  Phi <- eval.basis(1:n, fb)[, -1]
  
  x1 <- as.numeric(Phi %*% coef1)
  mixing <- as.numeric(Phi %*% coef2)
  x2 <- lambda*x1 + (1-lambda)*mixing
  
  
  # construct trends
  x1 <- x1 |> scale()
  x2 <- x2 |> scale()


  # compute ARMA autocovariance structure
  # ARMAacf can return theoretical autocorrs for ARMA given noise variance
  rho <- ARMAacf(ar = ar.coefs, ma = ma.coefs, lag.max = (window - 1))
  psi <- ARMAtoMA(ar = ar.coefs, ma = ma.coefs, lag.max = 200)

  # contains all MA coeffs
  psi_full <- c(1, psi)

  # gamma0 when innovation variance is assumed 1,(because variance is
  # scaled linearly and we can separate arma shape from noise magnitude)
  gamma0_unit <- sum(psi_full^2) # gamma(0) when sigma^2 = 1
  gamma_unit <- gamma0_unit * rho # gamma(k) when sigma^2 = 1

  # making k vector to iterate over
  k <- 1:(window - 1)
  # Equation for variance of MA of length W of a stationary process
  # plugging in gamma_unit which assumes innovation variance = 1
  sigma2_window_mean_unit <- (1 / window^2) * (window * gamma_unit[1] + 2 *
    sum((window - k) * gamma_unit[k + 1]))

  # fix S2_y to make it mean of sd of each series over a rolling time k
  # rolling average of each series
  loc_var_x1 <- roll_var(x1, width = window, center = TRUE, min_obs = 2)
  s2_y_obs_x1 <- mean(loc_var_x1, na.rm = TRUE)

  loc_var_x2 <- roll_var(x2, width = window, center = TRUE, min_obs = 2)
  s2_y_obs_x2 <- mean(loc_var_x2, na.rm = TRUE)


  # scale innovation sd for each series
  sigma2_x1 <- s2_y_obs_x1 / (lambda_target * sigma2_window_mean_unit)
  sigma_x1 <- sqrt(sigma2_x1)

  sigma2_x2 <- s2_y_obs_x2 / (lambda_target * sigma2_window_mean_unit)
  sigma_x2 <- sqrt(sigma2_x2)

  noise1 <- arima.sim(
    model = list(order = c(length(ar.coefs), 0, length(ma.coefs)), 
                 ar = ar.coefs, ma = ma.coefs),
    n = n,
    rand.gen = function(t) {
      rnorm(t, mean = 0, sd = sigma_x1)
    },
    n.start = 100
  )

  noise2 <- arima.sim(
    model = list(order = c(length(ar.coefs), 0, length(ma.coefs)), 
                 ar = ar.coefs, ma = ma.coefs),
    n = n,
    rand.gen = function(t) {
      rnorm(t, mean = 0, sd = sigma_x2)
    },
    n.start = 100
  )

  # add noise to drift
  y1 <- x1 + noise1
  y2 <- x2 + noise2

  if (plotit) {
    ylim <- c(-1.1, 1.1) * max(abs(c(x1, y1, y2)))
    plot(x1, type = "l", ylim = ylim)
    lines(y1, col = "red")
    lines(y2, col = "blue")
  }

  out <- list(y1 = y1, y2 = y2)
}

```

#### Graph Data
```{r}
generate_state_rate(decouple_rate = 0.5, decouple_strength = 3, plotit = TRUE) 
```



#### d simulation
```{r}
# N: number of simulations for each value of d
d_sim <- function(N = 5, decouple_rate = 1) {
  
  results <- list()

  for (i in 1:N) {
    cat("\nRunning simulation", i, "of", N, " for d_rate-value = ", decouple_rate, "\n")
    flush.console()

    x <- generate_state_rate(n = 500,
                           nb = 25,
                           sd0 = 2,
                           p = 2.5,
                           decouple_rate = decouple_rate,  
                           decouple_strength = 1,
                           
                           lambda_target = 0.5,
                           ar.coefs = c(0.8, 0.1),
                           ma.coefs = c(0.3),
                           window = 30,
                           plotit = FALSE
                           )

    nullmodel <- fit_null_model(x$y1,
      x$y2,
      q = NULL,
      h = NULL,
      alpha = 0.05,
      rho0 = 0,
      max_pq = 2
    )

    boot <- bootstrap_local_corr(nullmodel)

     results[[i]] <- data.frame(
      decouple_rate = decouple_rate,
      sim_n = i,
      entry_rate = boot[["expected_asymptotic"]][["entry_rate"]],
      p.entry = boot[["p_values"]][["entry_rate"]],
      mean_run_length = boot[["expected_asymptotic"]][["mean_run_length"]],
      p.length = boot[["p_values"]][["mean_run_length"]]
    )
     
  }
  bind_rows(results)
}
```



```{r}
drate_vals <- c(0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9)
drate_data <- map_dfr(drate_vals, ~ d_sim(N = 30, decouple_rate = .x))

write_csv(drate_data, "sim0-0.9_N30.csv")
```



#### Plots
```{r}
drate_data <- read_csv(here::here("sim0-10_N100.csv"))


new <- drate_data |>
  mutate(reject_entry = case_when(
    p.entry >= 0.05 ~ "no",
    p.entry < 0.05 ~ "yes"
  ),
  reject_length = case_when(
    p.length >= 0.05 ~ "no",
    p.length < 0.05 ~ "yes")
  ) |>
  group_by(decouple_rate) |>
  summarise(
    n_sim = n(),                           
    n_reject1 = sum(reject_entry == "yes", na.rm = TRUE),
    n_reject2 = sum(reject_length == "yes", na.rm = TRUE),
    prop_reject_entry = n_reject1 / n_sim,
    prop_reject_length = n_reject2 / n_sim        
  ) |>
  ungroup() |>
  mutate(
    var_entry = (prop_reject_entry * (1 - prop_reject_entry)) / n_sim,
    se_entry  = sqrt(var_entry),
    var_length =  (prop_reject_length * (1 - prop_reject_length)) / n_sim,
    se_length  = sqrt(var_length),
  )


p1 <- new |>
  ggplot(aes(x = decouple_rate, y = prop_reject_entry)) +
  geom_point(size = 5) +
  geom_errorbar(
    aes(
      ymin = prop_reject_entry - se_entry,
      ymax = prop_reject_entry + se_entry
    ),
    width = 0.03
  ) +
  geom_smooth(se = FALSE) +
  theme_minimal(base_size = 18) +
  labs(title = "Entry Rate",
       x = "decouple rate value",
       y = "",
       subtitle = "P(reject)") +
  scale_x_continuous(breaks = scales::breaks_width(0.1)) +  
  theme(
    plot.title = element_text(size = 22),
    axis.title.x = element_text(size = 18),
    axis.text = element_text(size = 18),
    panel.grid.minor = element_blank()
  )

p1

p2 <- new |>
ggplot(aes(x = decouple_rate, y = prop_reject_length)) +
  geom_point(size = 5) +
  geom_errorbar(
    aes(
      ymin = prop_reject_length - se_length,
      ymax = prop_reject_length + se_length
    ),
    width = 0.03
  ) +
  geom_smooth(se = FALSE) +
  theme_minimal(base_size = 18) +
  labs(title = "Length",
       x = "decouple rate value",
       y = "",
       subtitle = "P(reject)") +
  scale_x_continuous(breaks = scales::breaks_width(0.1)) +  
  theme(
    plot.title = element_text(size = 22),
    axis.title.x = element_text(size = 18),
    axis.text = element_text(size = 18),
    panel.grid.minor = element_blank()
  )

p2

```

- val
